language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: iJyKyKHjT5k36cbeJpZlzkR76YmXBbbVZEgENlVoOqcpKVYPsla2WLYLcFLO/4bNdw9n9lBRxUZIoqmadqkPXCHNmrIHoRAmUBuNEcrkHVMVQm1VP6NTRyezDnmrb+mrlpcQ1OzKoRwX0ZrYo55bo3oscgZ+GLFoFeeK2x9h7sLiT9mS6w/vJa9IPs9a1ZBC3NDCunhiCBhubU9U74zoowVNGXMUIEMiVyRDp7r3dWshFhlQiIh0ll+/Aa35GsXkAyDIyK6t1LBhlxCoiANdaHKNZViTSie7XP02WtWlhwfdg/aBZFodpXVFqgjbp67dUAe2ZM4gQkghOHWaUGPpnFMDZvc0/C7Pc2906yv3V3aOdBPoL4FJSr021YoUfX7b6PSrA2F67V0UpFKFrMmP9xj242IBDrGiN+FZKYfWRB1vS4HJkCls1v5adLNzoPxBOF8bZcx5sNkRd3BiSsaMMbTXap6EUZ6nHeIOhDlJ9gw2a5NMRRKPEGhMQFcgP6IqoJndL8YlF4gQPNSTP43YdiB/lzoruWjOFixWc+uXF9v6DQ2pVrrhmpHEtA50MuAwLZP+1hubsD4RNyHOD5kj0rb9/NnbmsJiE/yy1JQYxM97oAgIomtboygA4JtTxLCvFQ5BfXFhFqPjpiQcQgPo47u0vmhXkdqTARN/TVRfOwI=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: StygiIZOGyeAWzonbMmkvNhNKcPRUML9KMaKZWjRoh3OA4EJLzlnbSSkLeMhUG3bktJfe0mLoenTBuKyuECJr97CIK5AkzDHX7QVbMFnLReEHbY8Oq+oYwFvThBbFlkuz7rcA1bMunTx3DUtNR3/aJIarglo4LVnCI2GVWDBfEu8W1JHcXS1crOyj6xcdK+kwULn7a8v4E0gpe79oGX0t/91+wIYSb1Vgk6+eLN/yBALimr9wSV2FdnfnekKXqMV6VS/9sPT/wCq0NG6GWp027QkgapM/r/zFus2D2r7Okz3jTDBlSCebvwtfWYplyw70KvCQoh5jzZ4eQCR7QR22i69su1XLpeV2zwkrNewJvCS6Ma0W9sbZy22P7vY7xmZOZy0qQ/oEcf8K0PkMUsTBOhvJ1Nu/JXGxwAWTA5b3Se8XJEdXyFNZ88UFMWKJhkkjlasJaEkGKODrcI7DvR/esuXcjIXhmxYgXPUGQ+Obk4scXs5hEg5ORlKQcvfCEqnLsEchfg4S0Oj1eoPlnIDGnyN6QNdkGhJgKZ7ra8HZCBlkWpojEWmHV35yDd1XxEdbyrrAm4SG4v1RWFizyIrneKG7VRKlPKplN61ARg7hp5D29hA2iQGZh8pRQpfI1ZCyUJZxvBY+Crx3u+Vc0OLNeQqHPdK2ICa4cC0xGhL/3Q=
sudo: false
